Implemented the ISoulbound interface.
daccred/contracts pull request #10
Opened 2022-06-18 08:39 UTC by 0xfps

## Implemented the ISoulbound interface and IERC721Extension interface.

Added the ISoulbound interface and IERC721Extension interface.

## Environment

- Compiler version: 0.8.7
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Remix

- Operating system: Windows

## ISoulbound interface and IERC721Extension interface.

In response to issue #2 and #4, the ISoulbound and IERC721Extension interfaces have been added to the codebase.

2022-06-18 13:53 UTC, 0xfps commented
Also added interface for issue #4.

2022-06-19 05:50 UTC, koolamusic requested changes
Looks  good to me. 
Taking a look at the `isMinted` function I think we can have more use for it by leveraging it to write a `balanceOf` function that can return `0 or 1` where

- isMinted evaluates to `true` will return 1
- isMinted evals to `false` will return 0

This maintains compatibility with wallets and indexers but relies on the mechanisms we've defined in soulbound tokens

2022-06-19 05:50 UTC, koolamusic commented on src/contracts/interfaces/ISoulbound.sol
> +
Add the draft `EIP` we derived this from at the top

2022-06-19 05:50 UTC, koolamusic commented on src/contracts/interfaces/ISoulbound.sol
> +    function ownerOfToken(uint256 _tokenId) external returns(address);
We should strive to maintain compatibility with the ERC721 spec. So I think we could keep this as `ownerOf`

2022-06-19 05:53 UTC, koolamusic commented on src/contracts/interfaces/ISoulbound.sol
> +    function revoke(address _from, uint256 _tokenId) external returns(bool);
This revoke should only happen by `issuer` so something like a modifier for `onlyIssuer` would apply in this case

2022-06-19 11:54 UTC, 0xfps commented
I have made necessary changes.

2022-06-19 14:22 UTC, 0xfps commented
Also, added the interface for the POAP smart contract for issue #1.

2022-06-19 14:27 UTC, koolamusic approved these changes

2022-06-19 14:27 UTC, merged