Added the DaccredBase contract.
daccred/contracts pull request #15
Opened 2022-06-25 18:14 UTC by 0xfps

# 6
DaccredBase.all

Fixes #12 

## Added the DaccredBase contract.

Added the DaccredBase contract, required according to issue #12 .

Environment

| Environment                                       | Version           |
| ------------------------------------------------- | ----------------- |
| Compiler version                                  |  0.8.7   |
| Target EVM version (as per compiler settings):    |  default  |
| Framework/IDE (e.g. Truffle or Remix)             |  Remix    |
| Operating system (macOS / Windows)                |  Windows   |

### Description

The complete implementation is the DaccredBase contract was added, this will be deployed by the Factory when written.

2022-06-25 22:49 UTC, koolamusic commented
this is gonna take a while

2022-06-26 05:17 UTC, 0xfps commented
Ok.

2022-07-03 14:37 UTC, koolamusic requested changes
left a few comments, however in order to be explicit. 

Let's copy this contract https://github.com/chiru-labs/ERC721A/blob/main/contracts/ERC721A.sol

about 95% of the definitions of the ERC721A should be the ERC721 Extension.
Base contract should inherit it with any other contracts we use to add auth or utility to `DaccredBase`

2022-07-03 14:37 UTC, koolamusic commented on src/contracts/DaccredBase.sol
> +        tokenName = _name;
this is a problem.
Variable names should be exact with the ERC specification. 

Ideally 
symbol
name
burnCounter
indext
tokenIndex
currentIndex


these are common variable names used across the 721 spec

2022-07-03 14:37 UTC, koolamusic commented on src/contracts/DaccredBase.sol
> +    uint256 private tokensBurned;
review these names

2022-07-04 19:02 UTC, 0xfps commented
> left a few comments, however in order to be explicit.
> 
> Let's copy this contract https://github.com/chiru-labs/ERC721A/blob/main/contracts/ERC721A.sol
> 
> about 95% of the definitions of the ERC721A should be the ERC721 Extension. Base contract should inherit it with any other contracts we use to add auth or utility to `DaccredBase`

I have effected the changes 😊.

2022-07-05 20:36 UTC, koolamusic commented
LGTM

2022-07-05 20:36 UTC, merged